### ISSUE TITLE
Pipeline commands

### ISSUE THREAD

**Issue by sipani909** [CiscoTestAutomation/jenkins_report_plugin#2]
What pipeline commands can I use to publish the results with this plugin?

**Comment by sipani909** [comment]
@bastell any updates on this? Is there a pipeline command I can use to publish the report?

**Comment by stevedhn** [comment]
Hi @sipani909 did you try this? https://github.com/CiscoTestAutomation/jenkins_report_plugin/blob/master/guide/quick_start.md

**Comment by sipani909** [comment]
hi @stevedhn I did and it works fine for a freestyle job in Jenkins. I am looking to see what can I use in a pipeline job to achieve the same.

**Comment by stevedhn** [comment]
This plugin is a legacy thing, so the command to publish the results is not available for now.
